#### Load Numpy library

In [2]:
import numpy as np

#### The Basics

In [3]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [4]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [5]:
# Get the dimension
a.ndim

1

In [6]:
# Get shape
b.shape

(2, 3)

In [7]:
#Get type
a.dtype

dtype('int32')

In [8]:
# Get size
a.itemsize

4

In [9]:
#Get total size
a.nbytes

12

#### Accessing/Changing specific elements, rows, columns etc


In [10]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [11]:
# Get specific element [ r,c]
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [12]:
# Get specific columns
a[:,2]

array([ 3, 10])

In [13]:
# Getting a little more fancy[startindex:endindex:stepsize]
a[0,1:-1:2]

array([2, 4, 6])

In [14]:
a[1,5]=20
a[:,2]=[1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


#### 3D example

In [16]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [20]:
# Get specific element
b[1,1,0]

7

#### Initialize differetn types of arrays

In [21]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [25]:
# All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [27]:
# Any other number
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [28]:
# Any number(full_like)
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [29]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.33339827, 0.2094591 ],
       [0.17246939, 0.88134097],
       [0.21544965, 0.05395264],
       [0.61930661, 0.07898951]])

In [30]:
#Random integer values
np.random.randint(4,8,size=(3,3))

array([[7, 5, 4],
       [5, 7, 7],
       [4, 5, 5]])

In [32]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [33]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [40]:
# How do you initialise this array.
output = np.ones((5,5))
print(output)
z = np.zeros((3,3))
z[1,1]=9
print(z)

output[1:4,1:4]=z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### Be carreful when copying arrays!!!

In [43]:
a = np.array([1,2,3])
b=a.copy()
b[0]=100
print(a)
print(b)

[1 2 3]
[100   2   3]


#### Mathematics

In [44]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [45]:
a

array([1, 2, 3, 4])

In [46]:
a-2

array([-1,  0,  1,  2])

In [47]:
a+2


array([3, 4, 5, 6])

In [48]:
a*2

array([2, 4, 6, 8])

In [49]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [50]:
b = np.array([1,0,1,0])
a+b

array([2, 2, 4, 4])

In [51]:
a**2

array([ 1,  4,  9, 16], dtype=int32)

#### Take the sin


In [52]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

#### Linear algebra

In [55]:
a = np.ones((2,3))
print(a)

b= np.full((3,2),2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [58]:
# Find the determinant
c= np.identity(3)
print(c)
np.linalg.det(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


1.0

#### Statistics

In [59]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [60]:
np.min(stats)

1

In [61]:
np.max(stats,axis = 1)

array([3, 6])

In [62]:
np.sum(stats)

21

#### Reoraganising arrays


In [67]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((4,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [70]:
# Vetical stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
np.vstack([v1,v2,v1])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [71]:
# horizontal stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

#### Miscellaneous
Load data from file

In [74]:
filedata = np.genfromtxt('data.txt',delimiter = ',')
filedata =filedata.astype('int32')
filedata

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

#### Advanced indexing and Boolean masking

In [75]:
 filedata > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [76]:
 filedata[filedata > 50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88])

In [77]:
#  You can index with a list in Numpy
a= np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [79]:
np.any(filedata > 50 , axis=0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [80]:
np.all(filedata > 50 , axis=0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])